%% ---
%% id: 8e272f5a-6a4b-4839-871c-7f6a90310a61
%% ---
graph LR
  SM[Secret Manager] --> VPC
  OINTF["Operator Interface <br/> GCP Cloudshell"] --> VPC

  subgraph VPC["Single VPC"]
    SRC["Source VM<br/>pglogical publisher"] -->|PSA| DMS[DMS Replication Instance]
    DMS -->|PSA| DST["Cloud SQL<br/>PostgreSQL destination"]
  end