
graph LR
  SM[Secret Manager] --> VPC
  OINTF["Operator Interface <br/> GCP Cloudshell"] --> VPC

  subgraph VPC["Single VPC"]
    SRC["Source VM<br/>pglogical publisher"] -->|PSA| DMS[DMS Replication Instance]
    DMS -->|PSA| DST["Cloud SQL<br/>PostgreSQL destination"]
  end